---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - "host volume location here replace and remove quotes":/config
    ports:
      - 8444:8443
    restart: unless-stopped
