---
version: "2"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/bamboo/heimdall/config:/config
    ports:
      - 8080:80
      - 443:443
    restart: unless-stopped
